[package]
name = "rust-htslib-memleak-mre"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "memleak"
path = "src/main.rs"


[dependencies]
  rust-htslib = "0.44.1"
  rand        = "0.8"
